name: Test s2i installation
on: [push]

jobs:
  test-s2i-job:
    runs-on: ubuntu-latest
    name: A job to install s2i
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Run Hello World
        run: docker run hello-world
      - name: Checkout
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
      - name: Install and Test s2i
        uses: ./
        with:
          builder_image: "abc"
          image_name: "abc"
      - name: Test installation
        run: echo $(s2i version)
      - name: Build Image
        run: s2i build https://github.com/sclorg/django-ex centos/python-35-centos7 hello-python
